### ISSUE TITLE
Does not seem to work with different directory

### ISSUE THREAD

**Issue by brimwats1** [YunoHost-Apps/librephotos_ynh#13]
I have all of my media saved on `/var/Multimedia`  subfolders. For example, music is at `/var/Multimedia/Music.` 

Photos are saved at  `/var/Multimedia/Photos`. I tried to let Librephotos know this by going to Admin area -> and setting the user storage to `/var/Multimedia/Photos`. However, every time I saved it, it just resets to `/home/yunohost.app/librephotos/data/nextcloud_media'

[In the past](https://forum.yunohost.org/t/getting-jellyfin-and-nextcloud-on-the-same-page/12593/9) for YNH apps I have fixed this by adding apps to a group called Multimedia. That looks like this:

```
sudo su
usermod librephotos -a -G multimedia
# Set permissions
chown librephotos:multimedia -R /var/Multimedia
find /var/Multimedia -type d -exec chmod 0775 {} \;
find /var/Multimedia -type f -exec chmod 0664 {} \;
setfacl -d -m u::rwX,g::rwX,o::r /var/Multimedia
# Restart services
systemctl restart nginx
systemctl restart php7.3-fpm
systemctl restart php7.4-fpm
systemctl restart librephotos
```

However, this didn't seem to work in librephotos case. What am I missing?

**Comment by Jules-Bertholet** [comment]
Did you enable any of the Nextcloud integration options in LibrePhotos? If so you should disable them. By default, nothing at all should be stored in `/home/yunohost.app/librephotos/data/nextcloud_media`, and LibrePhotos should scan photos from `/home/yunohost.multimedia/<username>/Picture` (`/home/yunohost.multimedia` is a standard directory that many YunoHost packages use, it's set up almost exactly like you set up your `/var/Multimedia`). You can change the scan path for each user from the admin panel

**Comment by brimwats1** [comment]
> Did you enable any of the Nextcloud integration options in LibrePhotos? If so you should disable them. By default, nothing at all should be stored in `/home/yunohost.app/librephotos/data/nextcloud_media`, and LibrePhotos should scan photos from `/home/yunohost.multimedia/<username>/Picture` (`/home/yunohost.multimedia` is a standard directory that many YunoHost packages use, it's set up almost exactly like you set up your `/var/Multimedia`). You can change the scan path for each user from the admin panel

Well I only enabled them in that I tried to fill them out in the previous page. But that doesn't work because it won't save the password. I've tried deleting it, presing cancel, etc, and all it does it automatically refill it

**Comment by brimwats** [comment]
Here's a recording:

![oIWJKJzBoR](https://user-images.githubusercontent.com/49103046/116508136-89b65500-a875-11eb-8d71-a6e0aabd0482.gif)

**Comment by Jules-Bertholet** [comment]
I would guess this is an upstream bug, you will want to report it there. You can remove your Nextcloud credentials from your account manually with:
```
sudo sudo -u librephotos bash
/opt/yunohost/librephotos/bin/librephotos-cli shell
from django.contrib.auth import get_user_model
User = get_user_model()
user = User.objects.get(username='your_username')
user.nextcloud_app_password = None
user.nextcloud_scan_directory = None
user.nextcloud_server_address = None
user.nextcloud_username = None
user.save()
exit()
exit
```

**Comment by brimwats1** [comment]
thanks! I'll try reinstalling

**Comment by brimwats1** [comment]
I tried reinstalling but still cannot change anything in admin area :(

**Comment by Jules-Bertholet** [comment]
What happens when you try? Can you post a screenshot?

**Comment by brimwats1** [comment]
Step 1
![image](https://user-images.githubusercontent.com/49103046/116796358-9e226980-aa90-11eb-861d-884def7f5441.png)

Step 2
![image](https://user-images.githubusercontent.com/49103046/116796359-a1b5f080-aa90-11eb-94da-9950044ec98e.png)

Step 3. Refresh
Step 4: it's still the same:
![image](https://user-images.githubusercontent.com/49103046/116796362-a5497780-aa90-11eb-8549-d05ce9e98351.png)

**Comment by brimwats1** [comment]
I then tried to make a symlink:

ln -s /home/yunohost.multimedia/briwats/Picture /var/Multimedia/Picture

then I tried "scan photos: and still nothing

**Comment by Jules-Bertholet** [comment]
Can the `librephotos` user read the `/var/Multimedia` folder?

**Comment by brimwats1** [comment]
I don't know, that's what I'm asking, what I missed because I feel like I did 😢 

I did this  
```
sudo su
usermod librephotos -a -G multimedia
# Set permissions
chown librephotos:multimedia -R /var/Multimedia
find /var/Multimedia -type d -exec chmod 0775 {} \;
find /var/Multimedia -type f -exec chmod 0664 {} \;
setfacl -d -m u::rwX,g::rwX,o::r /var/Multimedia
# Restart services
systemctl restart nginx
systemctl restart php7.3-fpm
systemctl restart php7.4-fpm
systemctl restart librephotos
```

but it's not working so I feel like I am missing something

**Comment by Jules-Bertholet** [comment]
I think it may be that in your `setfacl` command you are not giving traverse permissions for directories to `other`. To match the permissions of `yunohost.multimedia` you want `sudo setfacl -nR -m g:multimedia:rwX,g::rwX,o:r-X -m d:g:multimedia:rwX,g::rwX,o:r-X "/var/Multimedia"`

**Comment by Jules-Bertholet** [comment]
You can always test with `sudo sudo -u librephotos ls /var/Multimedia/Picture`

**Comment by brimwats1** [comment]
`sudo sudo -u librephotos ls /var/Multimedia/Picture`

works! shows all the directories

> I think it may be that in your `setfacl` command you are not giving traverse permissions for directories to `other`. To match the permissions of `yunohost.multimedia` you want `sudo setfacl -nR -m g:multimediaA:rwX,g::rwX,o:r-X -m d:g:multimediaA:rwX,g::rwX,o:r-X "/var/Multimedia"`

I tried this 
```
setfacl -nR -m g:multimediaA:rwX,g::rwX,o:r-X -m d:g:multimediaA:rwX,g::rwX,o:r-x "/var/Multimedia"                                       
setfacl: Option -m: Invalid argument near character 3 
```
i noticed you had a cap A at the end of `multimediA`, so I removed that it and reran. The terminal seemed to be thinking for a bit. I then restarted everything via services webadmin and still get the same problem

**Comment by Jules-Bertholet** [comment]
Maybe check `journalctl`, or the logfiles under `/var/log/librephotos`? Otherwise I am stumped

**Comment by brimwats1** [comment]
Nothing there except system starting stuff :(

**Comment by Jules-Bertholet** [comment]
One last thing to try:
```
sudo sudo -u librephotos bash
/opt/yunohost/librephotos/bin/librephotos-cli shell
from django.contrib.auth import get_user_model
User = get_user_model()
user = User.objects.get(username='briwats')
user.scan_directory = '/var/Multimedia/Picture'
user.save()
exit()
exit
```

**Comment by brimwats1** [comment]
!! for the first time it's doing something!

![image](https://user-images.githubusercontent.com/49103046/116798585-062f7a80-aaa6-11eb-9922-65a19dd9433d.png)

**Comment by brimwats1** [comment]
it seems to be working now, but there's almost 100k photos for it to go through, so I'll report back! Thanks so much for the help!
