### ISSUE TITLE
Install fails on bullseye, no package 'ufraw-batch' anymore ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/librephotos_ynh#20]
c.f. https://packages.debian.org/buster/ufraw-batch and lack of 'bullseye' link in top right corner

Not sure what's supposed to replace this

**Comment by Jules-Bertholet** [comment]
Seems like it's only a soft dependency, I can add a check and make it optional

**Comment by Jules-Bertholet** [comment]
f10f191 fixes this

**Comment by charleslcso** [comment]
How to install ufraw-batch in Bullseye?
