### ISSUE TITLE
Installation abort at "Setting up backend" with a broken pipe error

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/librephotos_ynh#21]
### Describe the bug

The installation process is blocked at the step "Setting up backend" during long long time then abort after a broken pipe in the connection. It happened every time i tried.

### Context

- Hardware: desktop pc
- YunoHost version: 4.2.6
- I have access to my server: SSH and webmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?:  yes
  - If yes, please explain: looping script to correct regular deletion of resolv.dnsmasq.conf content
- Using, or trying to install package version/branch: testing

### Steps to reproduce

    ```
    sudo yunohost app install librephotos
     ```

### Expected behavior

Installation succeeds.

### Logs

https://paste.yunohost.org/raw/icokepilaq

**Comment by Jules-Bertholet** [comment]
Did you install via SSH? "broken pipe" would mean an SSH timeout in that case. You can tweak your `sshd` config to keep the connection alive, but a simpler solution would just be to press Enter every so often at the terminal, to keep the connection alive.

**Comment by tituspijean** [comment]
Another "safe" way to run long commands is to use a screen.

```
apt install screen
screen
# It will create a new empty prompt
yunohost app install ...
```

If connection breaks: `screen -R` to reconnect to the screen after logging in again in SSH.

---

Compiling sources can be very resource-consuming too. It is possible some services get killed by the system in the process, including the SSH connection.

How much RAM do you have? Could you consider stopping some of your largest apps while installing Librephotos? Or adding a swap file?

**Comment by stemy2** [comment]
You were right, installation was too heavy for my hardware.
